### ISSUE TITLE
左上角头像显示空白，点击进去显示undefined用户

### ISSUE THREAD

**Issue by Anynices** [kokdemo/v2ex.k#6]
登录/未登录都一样，以清除缓存试过。
配色左右反差有点大，不舒服.
右侧查看文章页面不显示作者头像，以及标题、内容、回复内容过长显示不全
附图：
https://ooo.0o0.ooo/2016/09/07/57cfe0f8db502.png

**Comment by kokdemo** [comment]
![image](https://cloud.githubusercontent.com/assets/825496/18501016/c67cba2a-7a7f-11e6-90e3-a75f395e2c47.png)

我这里看右边文章页面是这样的，是正常的。

如果可以的话，请你打开控制台，看一下右边这部分的css 宽度是不是有问题。

**Comment by kokdemo** [comment]
@AnythingLucky 忘了问，你觉得什么配色好一些呢？

**Comment by kokdemo** [comment]
头像的问题已经修复了。
