### ISSUE TITLE
Any convenient way to copy url?

### ISSUE THREAD

**Issue by tysheng** [kokdemo/v2ex.k#7]
Now the url is like https://www.v2ex.com/?tab=all&topicID=600400, it can't go to the right topic detail page, (should be https://www.v2ex.com/t/600400)
Any way to copy the right url?
Many thanks

**Comment by kokdemo** [comment]
I have fix this problem ，now you can get the url like 

"https://www.v2ex.com/?topicID=601735&iframe=https://www.v2ex.com/t/601735#reply64"

the last part is the origin url
